<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FindById</name>
   <tag></tag>
   <elementGuidId>832e58c5-bea7-4989-b495-39c8b710ac81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='${tableName}_Row_${rowName}_${columnName}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Table_Row_row_ColumnName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58f60d17-d280-4c47-b7a9-5088975aa09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Table_Row_row_ColumnName</value>
      <webElementGuid>e9345122-5ba3-4505-a417-9535a3ea97c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79d7e2e8-d361-47c0-85f3-1c23290a161d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>b9d94573-4cec-4405-894b-56082e23940c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FindById</value>
      <webElementGuid>aba21e8a-b0f6-413d-87cd-10321c38222a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Table_Row_row_ColumnName&quot;)</value>
      <webElementGuid>7e893977-9c0e-4c3b-8b57-66580cfc8a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Table_Row_row_ColumnName']</value>
      <webElementGuid>91464276-3cf1-488d-bb36-d737accb9742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/following::button[1]</value>
      <webElementGuid>1efac828-a554-4620-8d27-1eec7a9068db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[1]/following::button[1]</value>
      <webElementGuid>dce98d1f-24d6-4351-b41a-5c5196b194cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FindById']/parent::*</value>
      <webElementGuid>1920b084-812b-4861-b72e-e6273d033364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3ddd6306-c664-4df2-a027-3d5a08f35438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Table_Row_row_ColumnName' and @type = 'button' and (text() = 'FindById' or . = 'FindById')]</value>
      <webElementGuid>532228bc-60ec-4276-97f2-90be3c77198e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
